#!/bin/bash

# arguments
# inscop <original> <transformed_kernel> <output_file>

MAXLINES=`wc -l $1 | awk '{print $1}'`

grep -B $MAXLINES "#pragma[[:space:]]\+scop" $1 | grep -v "#pragma[[:space:]]\+scop" > .head
grep -A $MAXLINES "#pragma[[:space:]]\+endscop" $1 | grep -v "#pragma[[:space:]]\+endscop" > .tail

cat .head > __tmp

# The gcc preprocessor inserts some useless comments like "# 1 "<built-in>"
# preprocessor doesn't like pragma's in #defines and so it was not put in from pluto
# when '--bee' was used - instead we will add it here
cat $2 | grep "^#include" > .includes
cat $2 | grep -v "^#include" > .body.c
gcc -E -P -CC .body.c | grep -v "^# " | sed -e 's/schedule/#pragma schedule/' |  \
sed -e 's/_NL_DELIMIT_/\n/' >> __tmp

cat .tail >> __tmp

cat .includes > .head
echo "#include <math.h>" >> .head

echo "#define ceild(n,d)  ceil(((double)(n))/((double)(d)))" >> .head
echo "#define floord(n,d) floor(((double)(n))/((double)(d)))" >> .head
echo "#define max(x,y)    ((x) > (y)? (x) : (y))" >> .head
echo -e "#define min(x,y)    ((x) < (y)? (x) : (y))\n" >> .head

cat .head __tmp > $3

rm -f .head .tail __tmp .includes .body.c
