/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue Feb 16 12:45:56 1999
 */
#ifndef _alpha_h_
#define _alpha_h_
#if (defined(__STDC__) || defined(__cplusplus))

#if defined(__cplusplus)
extern "C" {
#endif

extern int GaussSimplify ( Matrix *M, Matrix *M2 );
extern int PolyhedronLTQ ( Polyhedron *P1, Polyhedron *P2, int INDEX, int
                           PDIM, int MAXRAYS );
extern int PolyhedronTSort ( Polyhedron ** L, unsigned int n, unsigned
                             int index, unsigned int pdim, int * time,
                             int * pvect, unsigned int MAXRAYS );
extern int Polyhedron_Not_Empty ( Polyhedron *P, Polyhedron *C, int
                                  MAXRAYS );
#if defined(__cplusplus)
}
#endif

#else /* (defined(__STDC__) || defined(__cplusplus)) */

extern int GaussSimplify (/* Matrix *M, Matrix *M2 */);
extern int PolyhedronLTQ (/* Polyhedron *P1, Polyhedron *P2, int INDEX,
                           int PDIM, int MAXRAYS */);
extern int PolyhedronTSort (/* Polyhedron ** L, unsigned int n, unsigned
                             int index, unsigned int pdim, int * time,
                             int * pvect, unsigned int MAXRAYS */);
extern int Polyhedron_Not_Empty (/* Polyhedron *P, Polyhedron *C, int
                                  MAXRAYS */);

#endif /* (defined(__STDC__) || defined(__cplusplus)) */
#endif /* _alpha_h_ */
