/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Mon Mar 30 11:33:17 1998
 */
#ifndef _errormsg_H_
#define _errormsg_H_
#if (defined(__STDC__) || defined(__cplusplus))

#if defined(__cplusplus)
extern "C" {
#endif

extern void errormsg1(char *f, char *msgname, char *msg);

#if defined(__cplusplus)
}
#endif

#else /* (defined(__STDC__) || defined(__cplusplus)) */

extern void errormsg1 (/* char *f, char *msgname, char *msg */);

#endif /* (defined(__STDC__) || defined(__cplusplus)) */
#endif /* _errormsg_H_ */
