/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Mon Mar 30 11:33:21 1998
 */
#ifndef _polyparam_H_
#define _polyparam_H_
#if (defined(__STDC__) || defined(__cplusplus))

#if defined(__cplusplus)
extern "C" {
#endif

extern void Compute_PDomains ( Param_Domain *PD, int nb_domains, int
                               working_space );
extern Param_Polyhedron *GenParamPolyhedron (Polyhedron *Pol);
extern void Param_Domain_Free (Param_Domain *PD);
extern void Param_Polyhedron_Free ( Param_Polyhedron *P );
extern void Param_Vertices_Free ( Param_Vertices *PV );
extern void Param_Vertices_Print ( FILE *DST, Param_Vertices *PV,
                                   char **param_names );
extern Polyhedron *PDomainDifference ( Polyhedron *Pol1, Polyhedron
                                       *Pol2, unsigned NbMaxRays );
extern Polyhedron *PDomainIntersection ( Polyhedron *Pol1, Polyhedron
                                         *Pol2, unsigned NbMaxRays );
extern Param_Polyhedron *Polyhedron2Param_Domain ( Polyhedron *Din,
                                                   Polyhedron *Cin, int
                                                   working_space );
extern Param_Polyhedron *Polyhedron2Param_SimplifiedDomain (
   Polyhedron **Din, Polyhedron *Cin, int working_space,
   Polyhedron **CEq, Matrix **CT );
extern Param_Polyhedron *Polyhedron2Param_Vertices ( Polyhedron *Din,
                                                     Polyhedron *Cin, int
                                                     working_space );
extern void Print_Domain ( FILE *DST, Polyhedron *D, char **param_names );
extern void Print_Vertex ( FILE *DST, Matrix *V, char **param_names );
extern Matrix *VertexCT( Matrix *V, Matrix *CT );

#if defined(__cplusplus)
}
#endif

#else /* (defined(__STDC__) || defined(__cplusplus)) */

extern void Compute_PDomains (/* Param_Domain *PD, int nb_domains, int
                               working_space */);
extern Param_Polyhedron *GenParamPolyhedron (/* Polyhedron *Pol */);
extern void Param_Domain_Free (/* Param_Domain *PD */);
extern void Param_Polyhedron_Free (/* Param_Polyhedron *P */);
extern void Param_Vertices_Free (/* Param_Vertices *PV */);
extern void Param_Vertices_Print (/* FILE *DST, Param_Vertices *PV,
                                  char **param_names */);
extern Polyhedron *PDomainDifference (/* Polyhedron *Pol1, Polyhedron
                                       *Pol2, unsigned NbMaxRays */);
extern Polyhedron *PDomainIntersection (/* Polyhedron *Pol1, Polyhedron
                                         *Pol2, unsigned NbMaxRays */);
extern Param_Polyhedron *Polyhedron2Param_Domain (/* Polyhedron *Din,
                                                   Polyhedron *Cin, int
                                                   working_space */);
extern Param_Polyhedron *Polyhedron2Param_SimplifiedDomain (/*
   Polyhedron **Din, Polyhedron *Cin, int working_space,
   Polyhedron **CEq, Matrix **CT */);
extern Param_Polyhedron *Polyhedron2Param_Vertices (/* Polyhedron *Din,
                                                     Polyhedron *Cin, int
                                                     working_space */);
extern void Print_Domain (/* FILE *DST, Polyhedron *D, char **param_names */);
extern void Print_Vertex (/* FILE *DST, Matrix *V, char **param_names */);
extern Matrix *VertexCT(/* Matrix *V, Matrix *CT */);

#endif /* (defined(__STDC__) || defined(__cplusplus)) */
#endif /* _polyparam_H_ */
