/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Fri May  5 14:40:37 2000
 */
#ifndef _SolveDio_h_
#define _SolveDio_h_
#if (defined(__STDC__) || defined(__cplusplus))

#if defined(__cplusplus)
extern "C" {
#endif

extern int SolveDiophantine ( Matrix *M, Matrix **U, Vector **X );

#if defined(__cplusplus)
}
#endif

#else /* (defined(__STDC__) || defined(__cplusplus)) */

extern int SolveDiophantine (/* Matrix *M, Matrix **U, Vector **X */);

#endif /* (defined(__STDC__) || defined(__cplusplus)) */
#endif /* _SolveDio_h_ */
