/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Wed Nov  3 13:25:01 1999
 */

#ifndef _Zpolyhedron_h_
#define _Zpolyhedron_h_
#if (defined(__STDC__) || defined(__cplusplus))

#if defined(__cplusplus)
extern "C" {
#endif

extern void CanonicalForm(ZPolyhedron *Zpol, ZPolyhedron **Result,
			  Matrix **Basis);
extern ZPolyhedron *EmptyZPolyhedron (int dimension);
extern ZPolyhedron *IntegraliseLattice (ZPolyhedron *A);
extern Bool isEmptyZPolyhedron (ZPolyhedron *Zpol);
extern ZPolyhedron *ZDomainDifference (ZPolyhedron *A, ZPolyhedron *B);
extern ZPolyhedron *ZDomainImage ( ZPolyhedron *A, Matrix *Func );
extern Bool ZDomainIncludes ( ZPolyhedron *A, ZPolyhedron *B );
extern ZPolyhedron *ZDomainIntersection ( ZPolyhedron *A, ZPolyhedron *B );
extern ZPolyhedron *ZDomainPreimage ( ZPolyhedron *A, Matrix *Func );
extern void ZDomainPrint ( FILE *fp, char *format, ZPolyhedron *A );
extern ZPolyhedron *ZDomainSimplify ( ZPolyhedron *ZDom );
extern ZPolyhedron *ZDomainUnion ( ZPolyhedron *A, ZPolyhedron *B );
extern ZPolyhedron *ZDomain_Copy ( ZPolyhedron *Head );
extern void ZDomain_Free ( ZPolyhedron *Head );
extern Bool ZPolyhedronIncludes ( ZPolyhedron *A, ZPolyhedron *B );
extern ZPolyhedron *ZPolyhedron_Alloc ( Lattice *Lat, Polyhedron *Poly );
extern ZPolyhedron *SplitZpolyhedron(ZPolyhedron *ZPol, Lattice *B);

#if defined(__cplusplus)
}
#endif

#else /* (defined(__STDC__) || defined(__cplusplus)) */

extern void CanonicalForm (/* ZPolyhedron *Zpol, ZPolyhedron **Result,
                            Matrix **Basis */);
extern ZPolyhedron *EmptyZPolyhedron (/* int dimension */);
extern ZPolyhedron *IntegraliseLattice (/* ZPolyhedron *A */);
extern Bool isEmptyZPolyhedron (/* ZPolyhedron *Zpol */);
extern ZPolyhedron *ZDomainDifference (/* ZPolyhedron *A, ZPolyhedron *B */);
extern ZPolyhedron *ZDomainImage (/* ZPolyhedron *A, Matrix *Func */);
extern Bool ZDomainIncludes (/* ZPolyhedron *A, ZPolyhedron *B */);
extern ZPolyhedron *ZDomainIntersection (/* ZPolyhedron *A, ZPolyhedron
                                          *B */);
extern ZPolyhedron *ZDomainPreimage (/* ZPolyhedron *A, Matrix *Func */);
extern void ZDomainPrint (/* FILE *fp, char *format, ZPolyhedron *A */);
extern ZPolyhedron *ZDomainSimplify (/* ZPolyhedron *ZDom */);
extern ZPolyhedron *ZDomainUnion (/* ZPolyhedron *A, ZPolyhedron *B */);
extern ZPolyhedron *ZDomain_Copy (/* ZPolyhedron *Head */);
extern void ZDomain_Free (/* ZPolyhedron *Head */);
extern Bool ZPolyhedronIncludes (/* ZPolyhedron *A, ZPolyhedron *B */);
extern ZPolyhedron *ZPolyhedron_Alloc (/* Lattice *Lat, Polyhedron *Poly */);
extern ZPolyhedron *SplitZpolyhedron(/*ZPolyhedron *ZPol, Lattice *B */);

#endif /* (defined(__STDC__) || defined(__cplusplus)) */
#endif /* _Zpolyhedron_h_ */
