#!/usr/bin/env python 
#
# orcc - Compile shell for Orio (C/C++ source code)
#

import src.main.main, sys
import warnings

warnings.simplefilter("ignore", DeprecationWarning)


src.main.main.start(sys.argv, src.main.main.C_CPP)

#import orio.main.main, sys
#orio.main.main.start(sys.argv, orio.main.main.C_CPP)

